name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

   # Set up Docker Buildx for multi-architecture builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

   # Cache Docker layers for faster builds
    - name: Cache Docker Layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-latest
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log into registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./app
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/trakt-to-toggl:latest
          ghcr.io/${{ github.repository_owner }}/trakt-to-toggl:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: ${{ github.event_name != 'pull_request' }}

  
